# Dependencies
markdown:            kramdown
highlighter:         rogue

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# Setup
title:               Pradipta Bora
tagline:             
description:         My personal website containing my blog, projects and reports/
url:                 http://geekpradd.github.io/
baseurl:             http://geekpradd.github.io/
# baseurl:             /
paginate:            5
paginate_path:       "/blog/page:num/"

# About/contact
author:
  name:              Pradipta Bora
  url:               https://twitter.com/mdo
  email:             pradiptabora@cse.iitb.ac.in

# Custom vars
version:             1.0.0
plugins:
  - jekyll-paginate
gems:
    - jekyll-redirect-from
