# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
# Setup
title:               GeekPradd
tagline:             'The Blog of Web developer Pradipta'
description:         'A Blog discussing science, programming and everything geeky'
url:                 http://geekpradd.github.io/
baseurl:             http://geekpradd.github.io/
paginate:            5

# About/contact
author:
  name:              Pradipta Bora
  url:               https://twitter.com/mdo
  email:             pradd@outlook.com

# Custom vars
version:             1.0.0
